### ISSUE TITLE
remote.go:35: extract packet and call packetFunc

### ISSUE THREAD

**Issue by 0pdd** [qapquiz/neowebsocket#1]
The puzzle `1-285316a5` from #1 has to be resolved: 

https://github.com/qapquiz/neowebsocket/blob/aa7e1da428d20f7bf93186cfa074eafcd4059688/pkg/websocket/remote.go#L35-L35

The puzzle was created by @qapquiz on 27-Jun-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1](https://github.com/qapquiz/neowebsocket/issues/1) is still not solved.

**Comment by qapquiz** [comment]
already close this issue but @0pdd  not close it.
